# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jeza/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7148.70/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/jeza/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7148.70/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeza/CLionProjects/muhash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeza/CLionProjects/muhash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/jeza/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7148.70/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/jeza/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/203.7148.70/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeza/CLionProjects/muhash/CMakeFiles /home/jeza/CLionProjects/muhash/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeza/CLionProjects/muhash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named muhash

# Build rule for target.
muhash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 muhash
.PHONY : muhash

# fast build rule for target.
muhash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/build
.PHONY : muhash/fast

chacha20.o: chacha20.cpp.o

.PHONY : chacha20.o

# target to build an object file
chacha20.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/chacha20.cpp.o
.PHONY : chacha20.cpp.o

chacha20.i: chacha20.cpp.i

.PHONY : chacha20.i

# target to preprocess a source file
chacha20.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/chacha20.cpp.i
.PHONY : chacha20.cpp.i

chacha20.s: chacha20.cpp.s

.PHONY : chacha20.s

# target to generate assembly for a file
chacha20.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/chacha20.cpp.s
.PHONY : chacha20.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/main.cpp.s
.PHONY : main.cpp.s

muhash.o: muhash.cpp.o

.PHONY : muhash.o

# target to build an object file
muhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/muhash.cpp.o
.PHONY : muhash.cpp.o

muhash.i: muhash.cpp.i

.PHONY : muhash.i

# target to preprocess a source file
muhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/muhash.cpp.i
.PHONY : muhash.cpp.i

muhash.s: muhash.cpp.s

.PHONY : muhash.s

# target to generate assembly for a file
muhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/muhash.cpp.s
.PHONY : muhash.cpp.s

uint256.o: uint256.cpp.o

.PHONY : uint256.o

# target to build an object file
uint256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/uint256.cpp.o
.PHONY : uint256.cpp.o

uint256.i: uint256.cpp.i

.PHONY : uint256.i

# target to preprocess a source file
uint256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/uint256.cpp.i
.PHONY : uint256.cpp.i

uint256.s: uint256.cpp.s

.PHONY : uint256.s

# target to generate assembly for a file
uint256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/uint256.cpp.s
.PHONY : uint256.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhash.dir/build.make CMakeFiles/muhash.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... muhash"
	@echo "... chacha20.o"
	@echo "... chacha20.i"
	@echo "... chacha20.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... muhash.o"
	@echo "... muhash.i"
	@echo "... muhash.s"
	@echo "... uint256.o"
	@echo "... uint256.i"
	@echo "... uint256.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

